//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectsManagementEntities : DbContext
    {
        public ProjectsManagementEntities()
            : base("name=ProjectsManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TAssistant> TAssistants { get; set; }
        public virtual DbSet<TAssistantHour> TAssistantHours { get; set; }
        public virtual DbSet<TAssistantToProject> TAssistantToProjects { get; set; }
        public virtual DbSet<TDestinationGroup> TDestinationGroups { get; set; }
        public virtual DbSet<TDestinationType> TDestinationTypes { get; set; }
        public virtual DbSet<TDocument> TDocuments { get; set; }
        public virtual DbSet<TDocumentType> TDocumentTypes { get; set; }
        public virtual DbSet<TGrade> TGrades { get; set; }
        public virtual DbSet<TListValue> TListValues { get; set; }
        public virtual DbSet<TMessage> TMessages { get; set; }
        public virtual DbSet<TParameter> TParameters { get; set; }
        public virtual DbSet<TPermission> TPermissions { get; set; }
        public virtual DbSet<TProfession> TProfessions { get; set; }
        public virtual DbSet<TProject> TProjects { get; set; }
        public virtual DbSet<TSchool> TSchools { get; set; }
        public virtual DbSet<TStatu> TStatus { get; set; }
        public virtual DbSet<TStudent> TStudents { get; set; }
        public virtual DbSet<TUser> TUsers { get; set; }
        public virtual DbSet<projects_students> projects_students { get; set; }
    }
}
