//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class projects_students
    {
        public int ProjectId { get; set; }
        public string ProjectName { get; set; }
        public Nullable<bool> Status { get; set; }
        public int IdUser { get; set; }
        public string fullname { get; set; }
    }
}
