//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAssistantHour
    {
        public int AssistantHoursId { get; set; }
        public Nullable<int> AssistantId { get; set; }
        public Nullable<System.DateTime> BeginningTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string WathToDo { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> finishChores { get; set; }
    
        public virtual TAssistant TAssistant { get; set; }
    }
}
