//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDestinationGroup
    {
        public int DestinationId { get; set; }
        public Nullable<int> GradeId { get; set; }
        public Nullable<int> DestinationTypeId { get; set; }
        public Nullable<int> DestinationDate { get; set; }
    
        public virtual TDestinationType TDestinationType { get; set; }
        public virtual TGrade TGrade { get; set; }
    }
}
