//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDestinationType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TDestinationType()
        {
            this.TDestinationGroups = new HashSet<TDestinationGroup>();
        }
    
        public int DestinationTypeId { get; set; }
        public string DestinationTypeName { get; set; }
        public Nullable<int> ProfessionId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDestinationGroup> TDestinationGroups { get; set; }
        public virtual TProfession TProfession { get; set; }
    }
}
