//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDocument
    {
        public int DocumentId { get; set; }
        public Nullable<int> DocumentTypeId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<System.DateTime> DateSubmission { get; set; }
        public Nullable<bool> IsApprove { get; set; }
    
        public virtual TDocumentType TDocumentType { get; set; }
        public virtual TProject TProject { get; set; }
    }
}
